spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
  logging:
    level:
      org.springdoc: DEBUG
      org.springframework.web: DEBUG

jwt:
  secretAccessKey: eTC7c0wlHf7QXdtQde2UGVab0rZVIU16jztlxm3VOmk=
  secretRefreshKey: ys1If+sHVaNZtoOildNWXp8Cu5ZsW+B6zQfzCd7pciE=
  expiration-time: 3600000 # 1시간 (밀리초 단위)