spring:
  profiles:
    active: mysql


jwt:
  secretAccessKey: eTC7c0wlHf7QXdtQde2UGVab0rZVIU16jztlxm3VOmk=
  secretRefreshKey: ys1If+sHVaNZtoOildNWXp8Cu5ZsW+B6zQfzCd7pciE=
  expiration-time: 3600000 # 1시간 (밀리초 단위)
---
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
  logging:
    level:
      org.springdoc: DEBUG
      org.springframework.web: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/springboard?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwer@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---